### ISSUE TITLE
future feature annotations is not defined

### ISSUE THREAD

**Issue by ThatGuyBob** [slavfox/jsom#1]
Can't import jsom module:

```
File "/home/bob/py37env/lib/python3.7/site-packages/jsom/__init__.py", line 4, in <module>
    from jsom.parser import JsomParser
  File "/home/bob/py37env/lib/python3.7/site-packages/jsom/parser.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

This is running Python 3.7 in a virgin virtualenv.  I get similar results using Py3.7 in the standard install directories as well.  (pip install jsom)

**Comment by the-moonwitch** [comment]
Sorry for the late response, I didn't get a notification for the issue.

[`annotations` are a part of the __future__ module since Python 3.7.0b1](https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations), so they should definitely be included in the stable release. Is this, by chance, on a Mac?

**Comment by ThatGuyBob** [comment]
Python 3.7.0a2 (default, Oct 18 2017, 18:58:26) 
On Ubuntu 18.04, "apt install python3" with the standard repositories gets you up to 3.6.7, so still not good enough.

I'll update my packages on this end and proceed.  I already got around this issue in my particular instance, so no need to keep this open.  Thank you for taking the time to look into it!  Hopefully this post helps someone else with a similar issue.
